import { Quicksand, Libre_Franklin } from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({
    variable: "--font-quicksand",
    subsets: ["latin"],
    display: "swap",
});

const libreFranklin = Libre_Franklin({
    variable: "--font-libre-franklin",
    subsets: ["latin"],
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body
                className={`${quicksand.variable} ${libreFranklin.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
