import Moomoo from "@/app/ui/Moomoo/Moomoo";

function cowPage() {
    return (
        <div>
            <div>MooMoo MoolahMate</div>
            <div>
                <Moomoo
                    size="interaction"
                    value="outfitsmoomoo"
                    src="/outfitsmoomoo.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="interaction"
                    value="outfitsmoomoo"
                    src="/eat.svg"
                />
            </div>
            <Moomoo
                size="interaction"
                value="outfitsmoomoo"
                src="/pet.svg"
            />
            <div>
                <Moomoo
                    size="interaction"
                    value="outfitsmoomoo"
                    src="/play.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="shop"
                    value="outfitsmoomoo"
                    src="/fancysuit.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="shop"
                    value="outfitsmoomoo"
                    src="/flower.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="shop"
                    value="outfitsmoomoo"
                    src="/icecream.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="shop"
                    value="outfitsmoomoo"
                    src="/kitty.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="shop"
                    value="outfitsmoomoo"
                    src="/puppy.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="shop"
                    value="outfitsmoomoo"
                    src="/royaldress.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="dressup"
                    value="outfitsmoomoo"
                    src="/sunglassmoomoo.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="dressup"
                    value="outfitsmoomoo"
                    src="/susmoomoo.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="dressup"
                    value="outfitsmoomoo"
                    src="/outfitsmoomoo.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="dressup"
                    value="outfitsmoomoo"
                    src="/bowmoomoo.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="goals"
                    value="outfitsmoomoo"
                    src="/moomoonormal.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="recommendationsgoals"
                    value="outfitsmoomoo"
                    src="/moomoonormal.svg"
                />
            </div>
            <div>
                <Moomoo
                    size="recommendationsgoals"
                    value="outfitsmoomoo"
                    src="/moomoonormal.svg"
                />
            </div>

            <div>
                <Moomoo
                    size="recommendationsgoals"
                    value="outfitsmoomoo"
                    src="/moomoolayingdown.svg"
                />
            </div>

            <div>
                <Moomoo
                    size="recommendationsgoals"
                    value="outfitsmoomoo"
                    src="/moomoosit.svg"
                />
            </div>

            <div>By: Thea C.</div>
        </div>
    );
}

export default cowPage;
